language: java
jdk:
- oraclejdk8
before_script:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn clean install sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=indrabasak-github
  -Dsonar.login=$SONAR_TOKEN
cache:
  directories: "– $HOME/.m2 – $HOME/.sonar/cache"
notifications:
  email:
  - indra.basak1@gmail.com
  on_success: change
  on_failure: always
  use_notice: true
env:
  global:
    secure: lk8usqDCVOrRz4Cx1FzCnBtrZTL77fxweB5IBocnaop5MwUGW58xcsMSGw4luF4DLd4EfCVUzfzSwAypzvD2rL99641H4m2nKYMk4HGK5+Ml5FQ/UvR31vZEaGMjaDHawS6viqsakOHwoZu7xDwMUB+kshwym7I3mW4XnRA9i1lkXrilOzpeXB1aFbVXaS8CSg2zQWCYanO/T9n7C7W1FduQeY1JRYY9rykynbeOICruZw0y33P4dOCFYqiql85vYmc2fbXNaF4H7xNURWlJEGff8UFIeOLhYdZ8TfVjZVyRp7+ChIFzRYnF4EuvwLlAXa4vuSoliu/U2Gd2dzqnfkg53+InZ+9exOemTG+r0tMsJMfPlUL4A7xVluqSF5EuFD3bftzlD4Bqxyv50NqqzOnPvMQ+C7mPtfsc+sQZrrNMz+ahbpKWdNW71wnrYvx3/Cc3jq9iejFzlrIc6+vI+RXkNfJWUlRtZU58J0Hmm+PpxzhWFnk7O3TOiMESw1VraZSVb/8ZVRy8djlYfH3dhVX9A9pEIJdm7fXeW38Dh19lbNngVwyttcnCcXs2uW9ocDXh85P7NbuXlvvFtTl17JFVPql71/KJUmwvAWyNAXixdS7pP6yq6/l1QOeLhLOzXmso7IJrGZ4pDDYS46m4YqEg1DF1Dfxi6HhSSQaLLXM=
